# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happypiggybank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='file',
        ),
        migrations.AddField(
            model_name='story',
            name='files',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
