# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happypiggybank', '0002_auto_20171011_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='is_read',
        ),
        migrations.AddField(
            model_name='story',
            name='read_times',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
