# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-15 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('happypiggybank', '0003_auto_20171011_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='HPBGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hpb_group',
            },
        ),
        migrations.CreateModel(
            name='UserHPBGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('hpb_group_id', models.BigIntegerField(db_index=True)),
            ],
            options={
                'db_table': 'user_hpb_group',
            },
        ),
        migrations.AddField(
            model_name='story',
            name='hpb_group_id',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
