# Generated by Django 2.0.1 on 2018-01-17 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('happypiggybank', '0004_auto_20171015_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'story_comment',
            },
        ),
    ]
