# Generated by Django 2.0.1 on 2018-01-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happypiggybank', '0006_story_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpbgroup',
            name='name',
            field=models.CharField(default='tungnt', max_length=100),
            preserve_default=False,
        ),
    ]
